services:
  api:
    container_name: "snippet-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: snippet-db
      DB_HOST: snippet-postgres_db
      DB_PORT: 5432
      SPRING_PROFILES_ACTIVE: production

  db:
    container_name: snippet-postgres_db
    image: postgres:17.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snippet-db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: