services:
  snippet-service:
    container_name: snippet-service
    build:
      context: .
    ports:
      - "8083:8080"
    environment:
      DB_HOST: snippet-db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVICE_ASSET_URL: ${SERVICE_ASSET_URL}
      SERVICE_ENGINE_URL: ${SERVICE_ENGINE_URL}
      SERVICE_AUTH_URL: ${SERVICE_AUTH_URL}
      AUTH0_ISSUER_URI: ${AUTH0_ISSUER_URI}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
    env_file:
      - .env
    depends_on:
      - snippet-db
    networks:
      - printscript-network

  snippet-db:
    container_name: snippet-postgres-db
    image: postgres:17.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - snippet-db-data:/var/lib/postgresql/data
    networks:
      - printscript-network

networks:
  printscript-network:
    driver: bridge

volumes:
  snippet-db-data:
